import type { Metadata } from "next";
import {Geist, Geist_Mono, Roboto} from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "900",
  subsets: ["latin"]
});


// export const metadata: Metadata = {
//   title: "My First Next App",
//   description: "Generated by Mithun",
// };

export const metadata: Metadata = {
  title: "My First Next.js App",
  description: "This app is created by Mithun Kumer Modak"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        
        <main className="min-h-dvh">
          {children}
        </main>
        
      </body>
    </html>
  );
}
